DEBUG = True
SQLALCHEMY_ECHO = True

SECRET_KEY = 'Sm9obiBTY2hyb20ga2lja3MgYXNz'
STRIPE_API_KEY = 'SmFjb2IgS2FwbGFuLU1vc3MgaXMgYSBoZXJv'

SQLALCHEMY_DATABASE_URI = 'sqlite:///../sqlite.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True